-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.friendships
(
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    user_1 text COLLATE pg_catalog."default",
    user_2 text COLLATE pg_catalog."default",
    status bigint,
    CONSTRAINT friendships_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.friendships
    OWNER to postgres;

ALTER TABLE IF EXISTS public.friendships
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.friendships TO anon;

GRANT ALL ON TABLE public.friendships TO authenticated;

GRANT ALL ON TABLE public.friendships TO postgres;

GRANT ALL ON TABLE public.friendships TO service_role;
