-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.show_media_types
(
    id bigint NOT NULL,
    created_at timestamp with time zone,
    type text COLLATE pg_catalog."default",
    CONSTRAINT show_media_types_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.show_media_types
    OWNER to postgres;

ALTER TABLE IF EXISTS public.show_media_types
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.show_media_types TO anon;

GRANT ALL ON TABLE public.show_media_types TO authenticated;

GRANT ALL ON TABLE public.show_media_types TO postgres;

GRANT ALL ON TABLE public.show_media_types TO service_role;
