-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.suggestions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    show_id bigint,
    user_id uuid,
    friendship_id bigint,
    show_media_type bigint,
    CONSTRAINT suggestions_pkey PRIMARY KEY (id),
    CONSTRAINT suggestions_friendship_id_fkey FOREIGN KEY (friendship_id)
        REFERENCES public.friendships (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT suggestions_show_media_type_fkey FOREIGN KEY (show_media_type)
        REFERENCES public.show_media_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT suggestions_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.suggestions
    OWNER to postgres;

ALTER TABLE IF EXISTS public.suggestions
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.suggestions TO authenticated;

GRANT ALL ON TABLE public.suggestions TO anon;

GRANT ALL ON TABLE public.suggestions TO service_role;

GRANT ALL ON TABLE public.suggestions TO postgres;
