-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.friendship_statuses
(
    id bigint NOT NULL,
    created_at timestamp with time zone,
    status text COLLATE pg_catalog."default",
    CONSTRAINT friendship_statuses_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.friendship_statuses
    OWNER to postgres;

ALTER TABLE IF EXISTS public.friendship_statuses
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.friendship_statuses TO anon;

GRANT ALL ON TABLE public.friendship_statuses TO authenticated;

GRANT ALL ON TABLE public.friendship_statuses TO postgres;

GRANT ALL ON TABLE public.friendship_statuses TO service_role;
