-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.friendships
    DISABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 );

ALTER TABLE IF EXISTS public.friendships
    RENAME id TO created_at;

ALTER TABLE public.friendships
    ALTER COLUMN created_at TYPE timestamp with time zone ;
ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE IF EXISTS public.friendships
    RENAME id TO updated_at;

ALTER TABLE public.friendships
    ALTER COLUMN updated_at TYPE timestamp with time zone ;
ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE IF EXISTS public.friendships
    RENAME id TO user_1;

ALTER TABLE public.friendships
    ALTER COLUMN user_1 TYPE uuid;
ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN user_1 DROP NOT NULL;

ALTER TABLE IF EXISTS public.friendships
    RENAME id TO user_2;

ALTER TABLE public.friendships
    ALTER COLUMN user_2 TYPE uuid;
ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN user_2 DROP NOT NULL;

ALTER TABLE IF EXISTS public.friendships
    RENAME id TO status;

ALTER TABLE IF EXISTS public.friendships
    ALTER COLUMN status DROP NOT NULL;
ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT friendships_status_fkey FOREIGN KEY (status)
    REFERENCES public.friendship_statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT friendships_user_1_fkey FOREIGN KEY (user_1)
    REFERENCES public.profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT friendships_user_2_fkey FOREIGN KEY (user_2)
    REFERENCES public.profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.friendship_statuses
    DISABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.show_media_types
    DISABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.suggestions
    DISABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
    ALTER COLUMN id TYPE uuid COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.profiles
    ALTER COLUMN id SET STORAGE PLAIN;

ALTER TABLE IF EXISTS public.profiles
    RENAME id TO updated_at;

ALTER TABLE public.profiles
    ALTER COLUMN updated_at TYPE timestamp with time zone  COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.profiles
    ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.profiles
    ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE IF EXISTS public.profiles
    ALTER COLUMN updated_at SET STORAGE PLAIN;
ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
